INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (1, '1984', 'George Orwell', 10.0, CURRENT_DATE);
INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (2, 'To Kill a Mockingbird', 'Harper Lee', 15.0, CURRENT_DATE);
INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (3, 'Pride and Prejudice', 'Jane Austen', 20.0, CURRENT_DATE);
INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (4, 'The Great Gatsby', 'F. Scott Fitzgerald', 20.0, CURRENT_DATE);
INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (5, 'Moby-Dick', 'Herman Melville', 20.0, CURRENT_DATE);
INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (6, 'The Catcher in the Rye', 'J.D. Salinger', 20.0, CURRENT_DATE);
INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (7, 'To the Lighthouse', 'Virginia Woolf', 20.0, CURRENT_DATE);
INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (8, 'Brave New World', 'Aldous Huxley', 20.0, CURRENT_DATE);
INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (9, 'The Lord of the Rings', 'J.R.R. Tolkien', 20.0, CURRENT_DATE);
INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (10, 'Harry Potter and the Sorcerers Stone', 'J.K. Rowling', 20.0, CURRENT_DATE);
INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (11, 'The Chronicles of Narnia', 'C.S. Lewis', 20.0, CURRENT_DATE);
INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (12, 'The Hobbit', 'J.R.R. Tolkien', 20.0, CURRENT_DATE);
INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (13, 'Jane Eyre', 'Charlotte Bronte', 20.0, CURRENT_DATE);
INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (14, 'Crime and Punishment', 'Fyodor Dostoevsky', 20.0, CURRENT_DATE);
INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (15, 'The Odyssey', 'Homer', 40.0, CURRENT_DATE);
INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (16, 'New Book 16', 'New Author 16', 20.0, CURRENT_DATE);
INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (17, 'New Book 17', 'New Author 17', 20.0, CURRENT_DATE);
INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (18, 'New Book 18', 'New Author 18', 20.0, CURRENT_DATE);
INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (19, 'The Alchemist', 'Paulo Coelho', 20.0, CURRENT_DATE);
INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (20, 'The Da Vinci Code', 'Dan Brown', 20.0, CURRENT_DATE);
INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (21, 'The Hobbit', 'J.R.R. Tolkien', 20.0, CURRENT_DATE);
INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (22, 'The Catcher in the Rye', 'J.D. Salinger', 20.0, CURRENT_DATE);
INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (23, 'The Chronicles of Narnia', 'C.S. Lewis', 20.0, CURRENT_DATE);
INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (24, 'The Picture of Dorian Gray', 'Oscar Wilde', 20.0, CURRENT_DATE);
INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (25, 'The Grapes of Wrath', 'John Steinbeck', 20.0, CURRENT_DATE);
INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (26, 'The Old Man and the Sea', 'Ernest Hemingway', 20.0, CURRENT_DATE);
INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (27, 'The Kite Runner', 'Khaled Hosseini', 20.0, CURRENT_DATE);
INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (28, 'The Hitchhikers Guide to the Galaxy', 'Douglas Adams', 20.0, CURRENT_DATE);
INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (29, 'The Lord of the Rings', 'J.R.R. Tolkien', 20.0, CURRENT_DATE);
INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (30, 'The Great Gatsby', 'F. Scott Fitzgerald', 20.0, CURRENT_DATE);
INSERT INTO BOOKS (id, title, author, price, publish_date) VALUES (31, 'Brave New World', 'Aldous Huxley', 20.0, CURRENT_DATE);
